# 1. NumPy Arrays (Array Berdimensi N)
Array NumPy, juga dikenal sebagai ndarray, adalah struktur data fundamental dalam NumPy.
Mereka adalah kumpulan elemen yang tersusun dalam bentuk matriks dengan dimensi yang dapat diatur.

In [2]:
# Import library NumPy
import numpy as np

# Membuat array 1D
arr_1d = np.array([1, 2, 3, 4, 5])
# Membuat array 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Array NumPy dapat memiliki dimensi yang lebih tinggi juga.
# Membuat array 3D
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print('Array 1D:', arr_1d)
print('Array 2D:', arr_2d)
print('Array 3D:', arr_3d)

Array 1D: [1 2 3 4 5]
Array 2D: [[1 2 3]
 [4 5 6]]
Array 3D: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Anda dapat menggunakan atribut 'shape' untuk melihat dimensi array.
shape_arr_1d = arr_1d.shape
shape_arr_2d = arr_2d.shape
shape_arr_3d = arr_3d.shape

print('Array 1D:', shape_arr_1d)
print('Array 2D:', shape_arr_2d)
print('Array 3D:', shape_arr_3d)

Array 1D: (5,)
Array 2D: (2, 3)
Array 3D: (2, 2, 2)


In [5]:
# Anda juga dapat menggunakan fungsi len() untuk mendapatkan panjang array dalam dimensi pertama.
panjang_dimensi_pertama = len(arr_3d)  # Hasilnya 2 karena ada dua matriks dalam dimensi pertama
panjang_dimensi_pertama

2

In [6]:
# Array NumPy memungkinkan operasi matematika yang efisien pada seluruh array atau elemen-elemennya.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hasil_penjumlahan = arr1 + arr2  # Menghasilkan [5, 7, 9]
hasil_penjumlahan

array([5, 7, 9])