# 2. Pembuatan Array Menggunakan Fungsi Bawaan
NumPy menyediakan berbagai fungsi bawaan untuk membuat array dengan berbagai bentuk dan isi.

In [1]:
# Import pustaka NumPy
import numpy as np

# Membuat array 1D dengan angka acak
arr_random = np.random.rand(5)  # Array 1D dengan 5 angka acak antara 0 dan 1
arr_random

array([0.97765708, 0.12866118, 0.42888503, 0.40974849, 0.80930577])

In [2]:
# Membuat array 2D dengan angka acak
arr_random_2d = np.random.rand(3, 4)  # Array 2D dengan 3 baris dan 4 kolom angka acak
arr_random_2d

array([[0.93093234, 0.81576116, 0.98601009, 0.46431546],
       [0.98798754, 0.64873114, 0.26377099, 0.24390898],
       [0.6650918 , 0.51211004, 0.61272848, 0.86416687]])

In [3]:
# Membuat array 1D dengan urutan angka
arr_range = np.arange(10)  # Array 1D dengan angka 0 hingga 9
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Membuat array 1D dengan angka dalam interval tertentu
arr_linspace = np.linspace(0, 1, 5)  # Array 1D dengan 5 angka antara 0 dan 1
arr_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
# Membuat array identitas (matrix identitas)
arr_identity = np.eye(3)  # Matriks identitas 3x3
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Membuat array dengan semua elemen bernilai nol atau satu
arr_zeros = np.zeros(4)  # Array 1D dengan 4 elemen bernilai 0
arr_ones = np.ones((2, 3))  # Array 2D dengan 2 baris dan 3 kolom, semua elemen bernilai 1

print('Zeros:', arr_zeros)
print('Ones:', arr_ones)

Zeros: [0. 0. 0. 0.]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Fungsi-fungsi ini memudahkan pembuatan array dengan berbagai karakteristik, yang berguna untuk analisis data dan komputasi ilmiah.

# Anda juga dapat mengubah bentuk array dengan menggunakan metode reshape.
arr_to_reshape = np.arange(12)  # Membuat array 1D dengan 12 elemen
reshaped_arr = arr_to_reshape.reshape(3, 4)  # Mengubahnya menjadi array 2D dengan 3 baris dan 4 kolom

print('Array awal:', arr_to_reshape)
print('Array reshaped:', reshaped_arr)

Array awal: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
