## 3. Random Sampling dalam NumPy
NumPy menyediakan fungsi untuk menghasilkan angka acak dari berbagai distribusi.

In [2]:
# Import pustaka NumPy
import numpy as np

# Menghasilkan matriks 3x3 dengan angka acak dari distribusi normal dengan rata-rata 0 dan deviasi standar 1
random_normal = np.random.normal(0, 1, size=(3, 3))
random_normal

array([[ 2.25418719, -2.04033063, -0.65345299],
       [-0.89533699,  2.05498587, -1.13978748],
       [ 0.22189331, -0.29945803, -0.09438236]])

In [3]:
# Menghasilkan array dengan 5 angka acak dari distribusi uniform antara 0 dan 1
random_uniform = np.random.uniform(0, 1, size=5)
random_uniform

array([0.77233006, 0.17552804, 0.64861479, 0.79646052, 0.41992364])

In [4]:
# Menghasilkan matriks 2x4 dengan angka acak bulat antara 1 dan 10
random_integers = np.random.randint(1, 11, size=(2, 4))
random_integers

array([[ 6,  3,  2,  9],
       [10, 10,  4,  5]])

In [11]:
# Anda juga dapat mengacak urutan elemen dalam array.
arr_to_shuffle = np.array([1, 2, 3, 4, 5])
print('Array awal:', arr_to_shuffle)
np.random.shuffle(arr_to_shuffle)
print('Array shuffled:', arr_to_shuffle)

Array awal: [1 2 3 4 5]
Array shuffled: [4 5 3 1 2]
